# ----
# Site

title: Saylor Academy API
description: API documentation for Saylor Academy.
url: https://saylordotorg.github.io/api-docs/
google_analytics_key:

collections:
  documentation:
    title: Documentation
    position: 1
  api:
    title: APIs
    position: 2
  functions:
    title: Functions
    position: 3
gems:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - readme.md
  - LICENCE
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: default

# -----
# Build


# -----------
# CloudCannon

version: 3.0.3
